apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-words-db
spec:
  ports:
    - port: {{ default 5432 .Values.httpPort }}
      targetPort: 5432
      name: {{ .Release.Name }}-db
  selector:
    app: {{ .Release.Name }}-words-db
  clusterIP: {{ .Values.service.clusterIP }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-words-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-words-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-words-db
    spec:
      containers:
      - name: {{ .Release.Name }}-db
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.ports.containerPort }}
          name: {{ .Release.Name }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-words
  labels:
    app: {{ .Release.Name }}-words-api
spec:
  ports:
    - port: {{default 8080 .Values.httpPort}}
      targetPort: 8080
      name: {{ .Release.Name }}-api
  selector:
    app: {{ .Release.Name }}-words-api
  clusterIP: {{ .Values.service.clusterIP }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-words
  labels:
    app: {{ .Release.Name }}-words-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-words-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-words-api
    spec:
      containers:
      - name: {{ .Release.Name }}-words
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.ports.containerPort }}
          name: {{ .Release.Name }}-api
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: web
#  labels:
#    app: words-web
#spec:
#  ports:
#    - port: 8081
#      targetPort: 80
#      name: web
#  selector:
#    app: words-web
#  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name }}-words-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-words-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-words-web
    spec:
      containers:
      - name: {{ .Release.Name }}-web
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.ports.containerPort }}
          name: {{ .Release.Name }}-words-web
